### ISSUE TITLE
Links don't work

### ISSUE THREAD

**Issue by bladeswords** [AustralianCyberSecurityCentre/windows_event_logging#3]
Just tried to access the links in the readme that reference the primary document.  They don't work.

**Comment by wikijm** [comment]
Hi @bladeswords,

Please take a look at https://github.com/AustralianCyberSecurityCentre/windows_event_logging/pull/4

Sincerely,
WikiJM

**Comment by bladeswords** [comment]
Hopefully these get merged/fixed soon!

**Comment by ACSCUser1** [comment]
fixed, please let us know if there are any more. Main focus this year has been on the sysmon config, but included update to the README
