### ISSUE TITLE
accounts_logon error

### ISSUE THREAD

**Issue by bk-paradox** [AustralianCyberSecurityCentre/windows_event_logging#5]
in the config for account_logons_sub.xml
The explicit credentials have a typo.
*[EventData[(Data[@Name='ProcessName'] = 'C:\Windows\System32\inetsrv\w3wp.exe.exe')]] or
which should be changed to
*[EventData[(Data[@Name='ProcessName'] = 'C:\Windows\System32\inetsrv\w3wp.exe')]] or

**Comment by ACSCUser1** [comment]
thank you, fixed now
